
name: Lunar Veggie Reminder

on:
  schedule:
    - cron: "30 6 * * *"   # 每天 00:30 UTC → 台灣 08:30
  workflow_dispatch:       # 手動測試用

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run reminder
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}     # 多人用逗號分隔
          TZ: Asia/Taipei
        run: python lunar_veggie_messaging.py
