name: Lunar Veggie Reminder

on:
  schedule:
    - cron: "8 6 * * *"   # 05:48 UTC → 台灣 13:48
  workflow_dispatch:
    inputs:
      force:
        description: "強制推播（忽略是否為農曆 1/15）"
        type: boolean
        required: false
        default: false
      pretend_today:
        description: "把今天當作此日期 (YYYY-MM-DD)"
        type: string
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run reminder
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}   # 多人逗號分隔
          TZ: Asia/Taipei
          FORCE: ${{ inputs.force }}
          PRETEND_TODAY: ${{ inputs.pretend_today }}
        run: python lunar_veggie_messaging.py
