name: TEMP — List LINE Followers

on:
  workflow_dispatch:

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: List followers (userIds only)
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        run: |
          python - << 'PY'
          import os, requests
          token = os.environ["LINE_CHANNEL_ACCESS_TOKEN"]
          hdr = {"Authorization": f"Bearer {token}"}
          url = "https://api.line.me/v2/bot/followers/ids"
          start = None
          users = []
          while True:
            params = {"start": start} if start else None
            r = requests.get(url, headers=hdr, params=params, timeout=10)
            r.raise_for_status()
            j = r.json()
            users += j.get("userIds", [])
            start = j.get("next")
            if not start: break
          print("Followers userIds:")
          for u in users: print(u)
          print("Total:", len(users))
          PY
